### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by listepo**

### CODE REVIEW

**Comment by Kikobeats** [comment]
why not use 'latest' keyword for fetch the last version? could be dangerous?

**Comment by listepo** [comment]
I think that the danger can not be excluded in the api major versions

**Comment by Kikobeats** [comment]
hmmm in these case with ~ semver flag you can indicate that you just want include minor versions

**Comment by listepo** [comment]
:+1:

**Comment by Kikobeats** [comment]
are you tested the update version?

we can limit the version of the depency to `~1.x.x`

**Comment by listepo** [comment]
Yes

**Comment by Kikobeats** [comment]
update and I merge :-)

**Comment by Kikobeats** [comment]
@listepo waiting...

**Comment by listepo** [comment]
I see https://david-dm.org/Kikobeats/sails-hook-newrelic , ^1.17.1 include 1.19.2

**Pull request closed without merging**
